/* Base styles */
body {
  margin: 0;
  font-family: 'Helvetica Neue', sans-serif;
  background: #ffffff;
  color: #111;
  line-height: 1.6;
}

h1, h2, h3 {
  font-weight: 400;
}

a {
  color: inherit;
  text-decoration: none;
}

nav {
  display: flex;
  justify-content: space-between;
  padding: 20px 40px;
  border-bottom: 1px solid #eee;
  position: sticky;
  top: 0;
  background: #fff;
}

nav .logo {
  font-weight: bold;
  font-size: 1.2em;
}

nav ul {
  display: flex;
  gap: 20px;
  list-style: none;
}

header {
  text-align: center;
  padding: 100px 20px 60px;
}

header h1 {
  font-size: 2.5em;
}

section {
  padding: 60px 40px;
  max-width: 900px;
  margin: auto;
}

.timeline .job {
  margin-bottom: 40px;
}

.gallery {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 20px;
}

.project {
  position: relative;
  overflow: hidden;
}

.project img {
  width: 100%;
  display: block;
}

.project .overlay {
  position: absolute;
  bottom: 0;
  background: rgba(255,255,255,0.9);
  width: 100%;
  padding: 15px;
  transform: translateY(100%);
  transition: transform 0.3s ease;
}

.project:hover .overlay {
  transform: translateY(0);
}

.skills-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 10px;
  list-style: none;
  padding: 0;
  margin-top: 20px;
}

.skills-list li {
  border: 1px solid #ddd;
  padding: 10px;
  text-align: center;
  font-size: 0.95em;
}

footer {
  text-align: center;
  padding: 40px 20px;
  font-size: 0.85em;
  color: #888;
  border-top: 1px solid #eee;
}
